const fmt = (n) => Number(n).toLocaleString("en-IN");
// ─── TRANSLATIONS ────────────────────────────────────────────────────────────
const T = {
    en: {
      // Common
      back: "← Back",
      screen: "Step",
      of: "of",
      // Screen 1
      s1Title: "Your Business Today",
      s1Sub: "Tell us about your business and we'll show you exactly how to grow it.",
      s1Sales: "Monthly Sales (₹)",
      s1Margin: "Profit Margin (%)",
      s1MarginHint: "e.g. 20 means you keep 20% of sales as profit",
      s1Investment: "Capital Needed to Grow (₹)",
      s1Profit: "Your Monthly Profit",
      s1Challenges: "Your Challenges",
      s1Problem1: (m) => `Thin margins — hard to save capital`,
      s1Problem2: (y) => `Saving alone would take ${y} years`,
      s1Problem3: () => `Growth is stuck without outside capital`,
      s1Insight: (m, inv) => `At this pace, saving ₹${inv} will take ${m} months on your own.`,
      s1InsightSub: (y) => `${y} years of waiting — there's a better way.`,
      s1CTA: "Grow My Business →",
      // Screen 2
      s2Title: (inv) => `You need ₹${inv} to expand`,
      s2Sub: "Two paths. One costs you monthly. One grows with you.",
      s2Income: (i) => `Your current profit: ₹${i}/month`,
      s2Loan: "Bank Loan",
      s2LoanSub: "Fixed EMI every month",
      s2LoanDesc: "Whether business is good or bad — you pay the same fixed amount.",
      s2Partner: "Quiver Partnership",
      s2PartnerBadge: "Recommended",
      s2PartnerSub: "No fixed EMI. Your partner earns when you earn.",
      s2PartnerDesc: "Capital + Mentorship + Market Linkage — all in one.",
      s2SeeEMI: "See EMI Details →",
      s2Continue: "Continue →",
      s2Change: "Change",
      // Screen EMI
      sEMITitle: "Loan Calculator",
      sEMISub: "Explore repayment plans",
      sEMIDuration: "Repayment Duration",
      sEMIYrs: "yrs",
      sEMILoan: "Loan Amount",
      sEMIRate: "Interest Rate",
      sEMIMonthly: "Monthly EMI",
      sEMIInterest: "Total Interest",
      sEMITotal: "Total Payable",
      sEMIAfter: "Balance after EMI",
      sEMIPartner: "Explore Partnership →",
      sEMIContinue: "Proceed with Loan",
      // Screen 3
      s3Title: "Partnership Benefits",
      s3Before: "Before",
      s3After: "After",
      s3Small: "Small Shop",
      s3Big: "Expanded Business",
      s3WithQuiver: "With Quiver's network",
      s3Brings: "What Your Partner Brings:",
      s3Mentor: "Expert Mentorship",
      s3MentorDesc: "A Quiver mentor who has built businesses guides your decisions — not just money.",
      s3Market: "Market Linkage",
      s3MarketDesc: "Connections to buyers, distributors, and markets you can't reach alone.",
      s3Capital: "Investment Capital",
      s3CapitalDesc: (inv) => `₹${inv} to expand — no loan EMI hanging over you.`,
      s3Quote: `"With Quiver, I didn't just get money — I got a partner who knew the way."`,
      s3CTA: "See How Equity Works →",
      // Screen 4
      s4Title: "What is Equity?",
      s4Before: "Before",
      s4After: "After",
      s4YouBefore: "You: 100%",
      s4YouAfter: "You: 85%",
      s4Partner: "Partner: 15%",
      s4Clarify: (p) => `Your partner owns 15% equity, but only takes ${p}% of your monthly sales as royalty income.`,
      s4Key: "Key Insight:",
      s4KeyDesc: (p) => `Partner takes ${p}% royalty from your SALES — not your profit. You keep more!`,
      s4KeySub: "Even in a tough month, you never pay more than 3% of what you sold.",
      s4Sales: "Monthly Sales",
      s4Revenue: "Your Monthly Profit",
      s4YouKeep: "You Keep",
      s4PartnerGets: "Partner Gets",
      s4Royalty: "3% Royalty",
      s4Quote: `"I kept 85% of my business and grew it 80% — that's Quiver."`,
      s4CTA: "See Your Impact →",
      // Screen 5
      s5Title: "Your Success Story!",
      s5Sub: "आपका व्यवसाय फल-फूल रहा है",
      s5Complete: "Business Expansion Complete!",
      s5Growth: "Revenue Growth",
      s5Jobs: "Community Impact",
      s5JobsVal: "New jobs created in your community",
      s5Brand: `"Quiver is your investor, your mentor, and your market — all in one."`,
      s5Share: "Share Your Story:",
      s5WhatsApp: "Share on WhatsApp",
      s5Copy: "Copy Text",
      s5Copied: "Copied!",
      s5Quote: `"I built this with Quiver."`,
      s5Restart: "Try Another Business",
      // Loan Prep
      lpTitle: "How to Prepare for a Bank Loan",
      lpSub: "Practical steps before approaching your bank",
      lpWhat: "What you need before approaching a bank:",
      lp1Title: "Clean Financial Records",
      lp1Desc: "Bank statements for 6–12 months showing regular sales and cash flow. Cleaner records = faster approval.",
      lp2Title: "Improve Your Credit Score",
      lp2Desc: "Your personal credit score must be above 650–700. Pay off old loans, avoid new debt, settle pending dues.",
      lp3Title: "Required Documents",
      lp3Desc: "GST registration, PAN card, Aadhaar, business license, property docs, and last 2 years of tax returns.",
      lp4Title: "Best Banks to Approach",
      lp4Desc: "Start with your current bank, then try SBI, ICICI, HDFC, or regional cooperative banks for rural businesses.",
      lpTip: "Quick tip: While preparing your loan documents, also explore Quiver's partnership option — you might find better terms.",
      lpRestart: "Try Another Business",
    },
    hi: {
      back: "← वापस",
      screen: "चरण",
      of: "का",
      s1Title: "आपका व्यवसाय आज",
      s1Sub: "अपने व्यवसाय के बारे में बताएं और हम आपको बढ़ने का तरीका दिखाएंगे।",
      s1Sales: "मासिक बिक्री (₹)",
      s1Margin: "लाभ मार्जिन (%)",
      s1MarginHint: "जैसे 20 का मतलब है बिक्री का 20% आपका लाभ",
      s1Investment: "व्यवसाय बढ़ाने के लिए पूंजी (₹)",
      s1Profit: "मासिक लाभ",
      s1Challenges: "आपकी चुनौतियाँ",
      s1Problem1: () => `मार्जिन बहुत कम — पूंजी बचाना कठिन`,
      s1Problem2: (y) => `अकेले बचत करने में ${y} साल लगेंगे`,
      s1Problem3: () => `बाहरी पूंजी के बिना विकास रुका हुआ है`,
      s1Insight: (m, inv) => `इस गति से, ₹${inv} बचाने में ${m} महीने लगेंगे।`,
      s1InsightSub: (y) => `${y} साल का इंतजार — एक बेहतर रास्ता है।`,
      s1CTA: "मेरा व्यवसाय बढ़ाएं →",
      s2Title: (inv) => `आपको ₹${inv} की जरूरत है`,
      s2Sub: "दो रास्ते। एक हर महीने खर्च करता है। एक आपके साथ बढ़ता है।",
      s2Income: (i) => `आपका मौजूदा लाभ: ₹${i}/महीना`,
      s2Loan: "बैंक ऋण",
      s2LoanSub: "हर महीने तय EMI",
      s2LoanDesc: "चाहे व्यवसाय अच्छा हो या बुरा — एक ही तय राशि देनी होगी।",
      s2Partner: "Quiver साझेदारी",
      s2PartnerBadge: "अनुशंसित",
      s2PartnerSub: "कोई EMI नहीं। आपका साथी तभी कमाता है जब आप कमाते हैं।",
      s2PartnerDesc: "पूंजी + मेंटरशिप + बाजार संपर्क — सब एक जगह।",
      s2SeeEMI: "EMI विवरण देखें →",
      s2Continue: "आगे बढ़ें →",
      s2Change: "बदलें",
      sEMITitle: "ऋण कैलकुलेटर",
      sEMISub: "पुनर्भुगतान योजना चुनें",
      sEMIDuration: "पुनर्भुगतान अवधि",
      sEMIYrs: "वर्ष",
      sEMILoan: "ऋण राशि",
      sEMIRate: "ब्याज दर",
      sEMIMonthly: "मासिक EMI",
      sEMIInterest: "कुल ब्याज",
      sEMITotal: "कुल भुगतान",
      sEMIAfter: "EMI के बाद शेष",
      sEMIPartner: "साझेदारी देखें →",
      sEMIContinue: "ऋण के साथ आगे बढ़ें",
      s3Title: "साझेदारी के फायदे",
      s3Before: "पहले",
      s3After: "बाद में",
      s3Small: "छोटी दुकान",
      s3Big: "बड़ा व्यवसाय",
      s3WithQuiver: "Quiver के नेटवर्क के साथ",
      s3Brings: "आपका साथी क्या लाता है:",
      s3Mentor: "विशेषज्ञ मेंटरशिप",
      s3MentorDesc: "Quiver का मेंटर जिसने पहले व्यवसाय बनाए हैं — सिर्फ पैसा नहीं, मार्गदर्शन भी।",
      s3Market: "बाजार संपर्क",
      s3MarketDesc: "खरीदारों, वितरकों और ऐसे बाजारों से जुड़ाव जो अकेले नहीं मिल सकते।",
      s3Capital: "निवेश पूंजी",
      s3CapitalDesc: (inv) => `₹${inv} का विस्तार — बिना EMI के बोझ के।`,
      s3Quote: `"Quiver के साथ, मुझे सिर्फ पैसा नहीं मिला — एक ऐसा साथी मिला जो रास्ता जानता था।"`,
      s3CTA: "इक्विटी समझें →",
      s4Title: "इक्विटी क्या है?",
      s4Before: "पहले",
      s4After: "बाद में",
      s4YouBefore: "आप: 100%",
      s4YouAfter: "आप: 85%",
      s4Partner: "साथी: 15%",
      s4Clarify: (p) => `आपका साथी 15% इक्विटी का मालिक है, लेकिन केवल मासिक बिक्री का ${p}% रॉयल्टी लेता है।`,
      s4Key: "मुख्य बात:",
      s4KeyDesc: (p) => `साथी आपकी बिक्री से ${p}% रॉयल्टी लेता है — लाभ से नहीं। आप ज्यादा रखते हैं!`,
      s4KeySub: "मुश्किल महीने में भी, आप बिक्री के 3% से ज्यादा नहीं देते।",
      s4Sales: "मासिक बिक्री",
      s4Revenue: "आपका मासिक लाभ",
      s4YouKeep: "आप रखते हैं",
      s4PartnerGets: "साथी को मिलता है",
      s4Royalty: "3% रॉयल्टी",
      s4Quote: `"मैंने 85% व्यवसाय रखा और 80% बढ़ाया — यही है Quiver।"`,
      s4CTA: "अपना प्रभाव देखें →",
      s5Title: "आपकी सफलता की कहानी!",
      s5Sub: "Your business is flourishing",
      s5Complete: "व्यवसाय विस्तार पूर्ण!",
      s5Growth: "आय वृद्धि",
      s5Jobs: "सामुदायिक प्रभाव",
      s5JobsVal: "आपके समुदाय में नई नौकरियाँ",
      s5Brand: `"Quiver आपका निवेशक, मेंटर और बाजार — सब कुछ एक जगह है।"`,
      s5Share: "अपनी कहानी साझा करें:",
      s5WhatsApp: "WhatsApp पर शेयर करें",
      s5Copy: "टेक्स्ट कॉपी करें",
      s5Copied: "कॉपी हो गया!",
      s5Quote: `"यह मैंने Quiver के साथ बनाया।"`,
      s5Restart: "दूसरा व्यवसाय आजमाएं",
      lpTitle: "बैंक ऋण की तैयारी कैसे करें",
      lpSub: "बैंक जाने से पहले व्यावहारिक कदम",
      lpWhat: "बैंक जाने से पहले आपको क्या चाहिए:",
      lp1Title: "स्वच्छ वित्तीय रिकॉर्ड",
      lp1Desc: "6-12 महीनों के बैंक स्टेटमेंट जो नियमित बिक्री दर्शाएं। साफ रिकॉर्ड = तेज मंजूरी।",
      lp2Title: "क्रेडिट स्कोर सुधारें",
      lp2Desc: "आपका व्यक्तिगत क्रेडिट स्कोर 650-700 से ऊपर होना चाहिए। पुराने ऋण चुकाएं।",
      lp3Title: "जरूरी दस्तावेज",
      lp3Desc: "GST पंजीकरण, PAN कार्ड, आधार, व्यवसाय लाइसेंस, संपत्ति दस्तावेज और 2 साल का आयकर रिटर्न।",
      lp4Title: "किस बैंक से संपर्क करें",
      lp4Desc: "पहले अपने मौजूदा बैंक से शुरू करें, फिर SBI, ICICI, HDFC या सहकारी बैंक।",
      lpTip: "सुझाव: ऋण दस्तावेज तैयार करते समय Quiver की साझेदारी भी देखें — बेहतर शर्तें मिल सकती हैं।",
      lpRestart: "दूसरा व्यवसाय आजमाएं",
    }
  };

  export { T, fmt };