const fmt = (n) => Number(n).toLocaleString("en-IN");
// ─── TRANSLATIONS ────────────────────────────────────────────────────────────
const T = {
  en: {
    // Common
    back: "← Back",
    screen: "Step",
    of: "of",
    // Landing
    landingTitle: "We help your business grow",
    landingSub:
      "Quiver partners with small businesses with funding, guidance, and tools you actually need.",
    landingCTA: "Continue →",
    landingFunding: "Funding",
    landingFundingSub: "Money when you need to scale",
    landingMentorship: "Guidance",
    landingMentorshipSub: "Mentorship to make the right decisions",
    landingTools: "Education & Tools",
    landingToolsSub: "Learn and improve how you run the business",
    // Screen 1
    s1Title: "Your Business Today",
    s1Sub:
      "Tell us about your business and we'll show you exactly how to grow it.",
    s1Sales: "Monthly Sales (₹)",
    s1Margin: "Profit Margin (%)",
    s1MarginHint: "e.g. 20 means you keep 20% of sales as profit",
    s1Investment: "Capital Needed to Grow (₹)",
    s1Profit: "Your Monthly Profit",
    s1Insight: (m, inv) =>
      `At this pace, even reinvesting your entire profit will take ${m} months to save ₹${inv}.`,
    s2Insight: (m, inv) =>
      `Reinvesting your entire profit will take ${m} months to save ₹${inv}.`,
    s1CTA: "Grow My Business →",
    // Screen 2
    s2Title: (inv) => `You need ₹${inv} to expand`,
    s2Sub: "Two paths. One costs you monthly. The other grows with you.",
    s2Income: (i) => `Your current profit: ₹${i}/month`,
    s2Loan: "Bank Loan",
    s2LoanSub: "Fixed EMI every month",
    s2LoanDesc:
      "Whether business is good or bad — you pay the same fixed amount.",
    s2Partner: "Equity",
    s2PartnerBadge: "Recommended",
    s2PartnerSub: "No fixed EMI. Your partner earns when you earn.",
    s2PartnerDesc: "Capital + Mentorship + Market Linkage — all in one.",
    s2SeeEMI: "See EMI Details →",
    s2Continue: "Explore Equity →",
    s2Change: "Change",
    // Step 2 - table comparison
    s2TblCapital: "Capital to expand",
    s2TblCollateral: "Collateral required",
    s2TblFixedEmi: "Fixed EMI every month",
    s2TblMentorship: "Mentorship / guidance",
    s2TblEducationTools: "Education & Tools",
    s2TblMarketLinkage: "Market linkage / network",
    // Screen EMI
    sEMITitle: "Loan Calculator",
    sEMISub: "Explore repayment plans",
    sEMIDuration: "Repayment Duration",
    sEMIRateLabel: "Interest Rate",
    sEMIYrs: "yrs",
    sEMILoan: "Loan Amount",
    sEMIRate: "Interest Rate",
    sEMIMonthly: "Monthly EMI",
    sEMIInterest: "Total Interest",
    sEMITotal: "Total Payable",
    sEMIAfter: "Cash in hand",
    sEMIPartner: "Explore Partnership →",
    sEMIContinue: "Proceed with Loan",
    // Screen 3
    s3Title: "How Equity Works",
    s3HeroSub: "Follow Meena's journey from struggle to growth",
    s3Tag1: "The Business",
    s3Title1: "Meena's Tailoring Unit",
    s3MonthlyIncome: "Monthly Income",
    s3FundingNeeded: "Funding Needed",
    s3Tag2: "The Problem",
    s3Title2: "Loans Aren't Easy",
    s3Prob1: "Banks ask for collateral",
    s3Prob2: "EMI pressure every month",
    s3Prob3: "High interest cuts profits",
    s3Tag3: "The Solution",
    s3Title3: "An Equity Partner Steps In",
    s3Investment: "Investment",
    s3ExitAfter: "Exit After",
    s3ExitVal: "5 Years",
    s3Tag4: "Equity Split",
    s3Title4: "She Keeps Control",
    s3MeenaControl: "Meena — Full control",
    s3InvestorPartner: "Investor partner",
    s3TagRisk: "Shared Risk",
    s3TitleRisk: "If business slows down...",
    s3Risk1: "Meena is not alone in losses",
    s3Risk2: "Her partner also shares the downside",
    s3Risk3: "Together, they adjust and rebuild",
    s3Tag5: "The Outcome",
    s3Title5: "Meena's Business Grows",
    s3Out1: "New machines purchased",
    s3Out2: "Bigger clients & more orders",
    s3Out3: "Investor brings network & guidance",
    s3CTA: "Continue →",
    // Screen 4
    s5JourneyTitle: "Start Your Journey",
    s5JourneyHighlight: "Today",
    s5JourneySub:
      "You've seen how equity can grow your business. Take the next step with Quiver.",
    s5GetStarted: "Get started",
    s5ApplyTitle: "Apply on Quiver",
    s5ApplySub: "Start your onboarding",
    s5LearnTitle: "Learn More",
    s5LearnSub: "Visit quiver.in to explore how it works",
    s5Or: "or",
    s5Restart: "← Start over with different numbers",
    // Loan Prep
    lpExploreTitle: "Explore Official Schemes",
    lpExploreSub:
      "Visit these official government portals to check eligibility and apply directly.",
    lpScheme1Name: "Jansamarth Portal",
    lpScheme1Desc:
      "Official Government of India portal for business loan schemes",
    lpScheme2Name: "Udyam Registration",
    lpScheme2Desc: "Official MSME registration portal by Ministry of MSME",
    lpScheme3Name: "Startup India",
    lpScheme3Desc: "Government initiative for startup funding & support",
    lpDisclaimer:
      "These are official government websites. We do not guarantee eligibility or outcomes.",
    lpContinueEquity: "Continue with Equity Instead →",
  },
  hi: {
    back: "← वापस",
    screen: "चरण",
    of: "का",
    // Landing
    landingTitle: "हम आपका बिज़नेस बढ़ाते हैं",
    landingSub:
      "Quiver छोटे व्यवसायों के साथ साझेदारी करता है: पैसा, मार्गदर्शन और ज़रूरी टूल्स।",
    landingCTA: "जारी रखें →",
    landingFunding: "फंडिंग",
    landingFundingSub: "स्केल करने के लिए सही समय पर पैसा",
    landingMentorship: "मार्गदर्शन",
    landingMentorshipSub: "सही फैसले के लिए मेंटरशिप",
    landingTools: "शिक्षा और टूल्स",
    landingToolsSub: "सीखें और अपने बिज़नेस को बेहतर चलाएं",
    s1Title: "आपका व्यवसाय आज",
    s1Sub: "अपने व्यवसाय के बारे में बताएं और हम आपको बढ़ने का तरीका दिखाएंगे।",
    s1Sales: "मासिक बिक्री (₹)",
    s1Margin: "लाभ मार्जिन (%)",
    s1MarginHint: "जैसे 20 का मतलब है बिक्री का 20% आपका लाभ",
    s1Investment: "व्यवसाय बढ़ाने के लिए पूंजी (₹)",
    s1Profit: "मासिक लाभ",
    s1Challenges: "आपकी चुनौतियाँ",
    s1Insight: (m, inv) => `इस गति से, ₹${inv} बचाने में ${m} महीने लगेंगे।`,
    s2Insight: (m, inv) => `इस गति से, ₹${inv} बचाने में ${m} महीने लगेंगे।`,
    s1InsightSub: (y) => `${y} साल का इंतजार — एक बेहतर रास्ता है।`,
    s1CTA: "मेरा व्यवसाय बढ़ाएं →",
    s2Title: (inv) => `आपको ₹${inv} की जरूरत है`,
    s2Sub: "दो रास्ते। एक हर महीने खर्च करता है। दूसरा आपके साथ बढ़ता है।",
    s2Income: (i) => `आपका मौजूदा लाभ: ₹${i}/महीना`,
    s2Loan: "बैंक ऋण",
    s2LoanSub: "हर महीने तय EMI",
    s2LoanDesc: "चाहे व्यवसाय अच्छा हो या बुरा — एक ही तय राशि देनी होगी।",
    s2Partner: "साझेदारी",
    s2PartnerBadge: "अनुशंसित",
    s2PartnerSub: "कोई EMI नहीं। आपका साथी तभी कमाता है जब आप कमाते हैं।",
    s2PartnerDesc: "पूंजी + मेंटरशिप + बाजार संपर्क — सब एक जगह।",
    s2SeeEMI: "EMI विवरण देखें →",
    s2Continue: "साझेदारी समझें →",
    s2Change: "बदलें",
    // Step 2 - table comparison
    s2TblCapital: "स्केल करने के लिए पूंजी",
    s2TblCollateral: "लोन के लिए कोलैटरल",
    s2TblFixedEmi: "हर महीने फिक्स्ड EMI",
    s2TblMentorship: "मेंटरशिप / मार्गदर्शन",
    s2TblEducationTools: "शिक्षा और टूल्स",
    s2TblMarketLinkage: "बाजार संपर्क / नेटवर्क",
    sEMITitle: "ऋण कैलकुलेटर",
    sEMISub: "पुनर्भुगतान योजना चुनें",
    sEMIDuration: "पुनर्भुगतान अवधि",
    sEMIRateLabel: "ब्याज दर",
    sEMIYrs: "वर्ष",
    sEMILoan: "ऋण राशि",
    sEMIRate: "ब्याज दर",
    sEMIMonthly: "मासिक EMI",
    sEMIInterest: "कुल ब्याज",
    sEMITotal: "कुल भुगतान",
    sEMIAfter: "EMI के बाद शेष",
    sEMIPartner: "साझेदारी देखें →",
    sEMIContinue: "ऋण के साथ आगे बढ़ें",

    s3Title: "इक्विटी कैसे काम करती है",
    s3HeroSub: "मीना की संघर्ष से विकास तक की यात्रा",
    s3Tag1: "व्यवसाय",
    s3Title1: "मीना की टेलरिंग यूनिट",
    s3MonthlyIncome: "मासिक आय",
    s3FundingNeeded: "जरूरी पूंजी",
    s3Tag2: "समस्या",
    s3Title2: "लोन आसान नहीं है",
    s3Prob1: "बैंक गारंटी मांगता है",
    s3Prob2: "हर महीने EMI का बोझ",
    s3Prob3: "ब्याज से मुनाफा कम होता है",
    s3Tag3: "समाधान",
    s3Title3: "एक इक्विटी पार्टनर आता है",
    s3Investment: "निवेश",
    s3ExitAfter: "बाहर निकलने का समय",
    s3ExitVal: "5 साल",
    s3Tag4: "इक्विटी बंटवारा",
    s3Title4: "वह नियंत्रण रखती है",
    s3MeenaControl: "मीना — पूरा नियंत्रण",
    s3InvestorPartner: "निवेशक साथी",
    s3TagRisk: "साझा जोखिम",
    s3TitleRisk: "अगर व्यवसाय धीमा हो जाए...",
    s3Risk1: "मीना नुकसान में अकेली नहीं है",
    s3Risk2: "उसका पार्टनर भी नुकसान साझा करता है",
    s3Risk3: "दोनों मिलकर सुधार करते हैं और आगे बढ़ते हैं",
    s3Tag5: "परिणाम",
    s3Title5: "मीना का व्यवसाय बढ़ता है",
    s3Out1: "नई मशीनें खरीदी गईं",
    s3Out2: "बड़े ग्राहक और ज्यादा ऑर्डर",
    s3Out3: "निवेशक नेटवर्क और मार्गदर्शन लाता है",
    s3CTA: "आगे बढ़ें →",

    s5JourneyTitle: "अपनी यात्रा शुरू करें",
    s5JourneyHighlight: "आज",
    s5JourneySub:
      "आपने देखा कि इक्विटी आपका व्यवसाय कैसे बढ़ा सकती है। Quiver के साथ अगला कदम उठाएं।",
    s5GetStarted: "शुरू करें",
    s5ApplyTitle: "Quiver पर आवेदन करें",
    s5ApplySub: "अपना ऑनबोर्डिंग शुरू करें",
    s5LearnTitle: "और जानें",
    s5LearnSub: "यह कैसे काम करता है जानने के लिए quiver.in पर जाएं",
    s5Or: "या",
    s5Restart: "← अलग नंबरों के साथ दोबारा शुरू करें",

    lpExploreTitle: "सरकारी योजनाएं देखें",
    lpExploreSub:
      "पात्रता जांचने और सीधे आवेदन करने के लिए इन आधिकारिक सरकारी पोर्टल पर जाएं।",
    lpScheme1Name: "जनसमर्थ पोर्टल",
    lpScheme1Desc: "व्यवसाय ऋण योजनाओं के लिए भारत सरकार का आधिकारिक पोर्टल",
    lpScheme2Name: "उद्यम पंजीकरण",
    lpScheme2Desc: "MSME मंत्रालय का आधिकारिक MSME पंजीकरण पोर्टल",
    lpScheme3Name: "स्टार्टअप इंडिया",
    lpScheme3Desc: "स्टार्टअप फंडिंग और सहायता के लिए सरकारी पहल",
    lpDisclaimer:
      "ये आधिकारिक सरकारी वेबसाइटें हैं। हम पात्रता या परिणामों की गारंटी नहीं देते।",
    lpContinueEquity: "इसके बजाय इक्विटी के साथ आगे बढ़ें →",
  },
  as: {
    back: "← আগৰলৈ",
    screen: "ধাপ",
    of: "ৰ",
    landingTitle: "আমি আপোনাৰ ব্যৱসা বৃদ্ধি কৰাত সহায় কৰোঁ",
    landingSub:
      "Quiver সৰু ব্যৱসাৰ সৈতে কাম কৰে — পুঁজি, পৰামৰ্শ আৰু প্ৰয়োজনীয় সঁজুলি আগবঢ়ায়।",
    landingCTA: "আগবাঢ়ক →",
    landingFunding: "পুঁজি",
    landingFundingSub: "বৃদ্ধিৰ বাবে সঠিক সময়ত ধন",
    landingMentorship: "পৰামৰ্শ",
    landingMentorshipSub: "সঠিক সিদ্ধান্ত ল'বলৈ সহায়",
    landingTools: "শিক্ষা আৰু সঁজুলি",
    landingToolsSub: "শিকক আৰু ব্যৱসা ভালদৰে চলাওক",
    s1Title: "আপোনাৰ ব্যৱসা আজি",
    s1Sub: "আপোনাৰ ব্যৱসাৰ বিষয়ে কওক, আমি আপোনাক বৃদ্ধি পথ দেখাম।",
    s1Sales: "মাহেকীয়া বিক্ৰী (₹)",
    s1Margin: "লাভৰ শতাংশ (%)",
    s1MarginHint: "উদাহৰণ: 20 মানে বিক্ৰীৰ 20% আপোনাৰ লাভ",
    s1Investment: "বৃদ্ধিৰ বাবে প্ৰয়োজনীয় পুঁজি (₹)",
    s1Profit: "মাহেকীয়া লাভ",
    s1Insight: (m, inv) => `এই গতিত, ₹${inv} সঞ্চয় কৰিবলৈ ${m} মাহ লাগিব।`,
    s2Insight: (m, inv) => `এই গতিত, ₹${inv} সঞ্চয় কৰিবলৈ ${m} মাহ লাগিব।`,
    s1CTA: "মোৰ ব্যৱসা বৃদ্ধি কৰক →",
    s2Title: (inv) => `আপোনাক ₹${inv} পুঁজি লাগিব`,
    s2Sub: "দুটা পথ আছে। এটা প্ৰতি মাহে খৰচ লাগে। আনটো আপোনাৰ সৈতে বৃদ্ধি পায়।",
    s2Income: (i) => `বৰ্তমান লাভ: ₹${i}/মাহ`,
    s2Loan: "বেংকৰ ঋণ",
    s2LoanSub: "প্ৰতি মাহে নিৰ্দিষ্ট EMI",
    s2LoanDesc: "ব্যৱসা ভাল হওক বা বেয়া — EMI দিবই লাগিব।",
    s2Partner: "ইকুইটি",
    s2PartnerBadge: "সুপাৰিশ কৰা হৈছে",
    s2PartnerSub: "EMI নাই। আপুনি লাভ কৰিলে তেতিয়াহে তেওঁ লাভ কৰে।",
    s2PartnerDesc: "পুঁজি + পৰামৰ্শ + বজাৰ সংযোগ — সকলো একে ঠাইত।",
    s2SeeEMI: "EMI বিৱৰণ চাওক →",
    s2Continue: "ইকুইটি বুজক →",
    s2Change: "সলনি কৰক",
    s2TblCapital: "প্ৰয়োজনীয় পুঁজি",
    s2TblCollateral: "ঋণৰ জামিন",
    s2TblFixedEmi: "প্ৰতি মাহে EMI",
    s2TblMentorship: "পৰামৰ্শ",
    s2TblEducationTools: "শিক্ষা আৰু সঁজুলি",
    s2TblMarketLinkage: "বজাৰ সংযোগ",
    sEMITitle: "ঋণ কেলকুলেটৰ",
    sEMISub: "আপোনাৰ পৰিশোধ পৰিকল্পনা চাওক",
    sEMIDuration: "মুদত",
    sEMIRateLabel: "সুদৰ হাৰ",
    sEMIYrs: "বছৰ",
    sEMILoan: "ঋণৰ পৰিমাণ",
    sEMIRate: "সুদৰ হাৰ",
    sEMIMonthly: "মাহেকীয়া EMI",
    sEMIInterest: "মুঠ সুদ",
    sEMITotal: "মুঠ দিবলগীয়া",
    sEMIAfter: "হাতত থাকিব",
    sEMIPartner: "অংশীদাৰিত্ব চাওক →",
    sEMIContinue: "ঋণৰ সৈতে আগবাঢ়ক",
    s3Title: "ইক্যুইটি কেনেকৈ কাম কৰে",
    s3HeroSub: "মীনাৰ ব্যৱসাৰ বৃদ্ধি কাহিনী চাওক",
    s3Tag1: "ব্যৱসা",
    s3Title1: "মীনাৰ চিলাই ইউনিট",
    s3MonthlyIncome: "মাহেকীয়া আয়",
    s3FundingNeeded: "প্ৰয়োজনীয় পুঁজি",
    s3Tag2: "সমস্যা",
    s3Title2: "ঋণ লোৱা সহজ নহয়",
    s3Prob1: "বেংকে জামিন বিচাৰে",
    s3Prob2: "প্ৰতি মাহে EMI চাপ",
    s3Prob3: "সুদে লাভ কমায়",
    s3Tag3: "সমাধান",
    s3Title3: "এটা ইক্যুইটি অংশীদাৰ আহে",
    s3Investment: "বিনিয়োগ",
    s3ExitAfter: "সময়",
    s3ExitVal: "৫ বছৰ",
    s3Tag4: "ইক্যুইটি ভাগ",
    s3Title4: "তেওঁ নিয়ন্ত্ৰণ ৰাখে",
    s3MeenaControl: "মীনা — সম্পূৰ্ণ নিয়ন্ত্ৰণ",
    s3InvestorPartner: "বিনিয়োগকাৰী অংশীদাৰ",
    s3TagRisk: "যৌথ ঝুঁকি",
    s3TitleRisk: "যদি ব্যৱসা ধীৰ হয়...",
    s3Risk1: "মীনা ক্ষতিত একেলগে নহয়",
    s3Risk2: "তেওঁৰ অংশীদাৰে ক্ষতি ভাগ কৰে",
    s3Risk3: "দুয়োয়ে মিলি পুনৰ গঠন কৰে",
    s3Tag5: "ফলাফল",
    s3Title5: "ব্যৱসা বৃদ্ধি পায়",
    s3Out1: "নতুন যন্ত্ৰ কিনা",
    s3Out2: "বেছি ক্লায়েন্ট আৰু অৰ্ডাৰ",
    s3Out3: "নেটৱৰ্ক আৰু পৰামৰ্শ লাভ",
    s3CTA: "আগবাঢ়ক →",
    s5JourneyTitle: "আপোনাৰ যাত্ৰা আৰম্ভ কৰক",
    s5JourneyHighlight: "আজিৰে পৰা",
    s5JourneySub:
      "আপুনি দেখিলে কেনেকৈ ইক্যুইটি ব্যৱসা বৃদ্ধি কৰে। এতিয়া পৰৱৰ্তী ধাপ লওক।",
    s5GetStarted: "আৰম্ভ কৰক",
    s5ApplyTitle: "Quiver ত আবেদন কৰক",
    s5ApplySub: "অনবোর্ডিং আৰম্ভ কৰক",
    s5LearnTitle: "অধিক জানক",
    s5LearnSub: "কেনেকৈ কাম কৰে জানিবলৈ quiver.in চাওক",
    s5Or: "বা",
    s5Restart: "← নতুনকৈ আৰম্ভ কৰক",
    lpExploreTitle: "চৰকাৰী আঁচনি চাওক",
    lpExploreSub: "যোগ্যতা চাওক আৰু সোজাকৈ আবেদন কৰক।",
    lpScheme1Name: "জনসমৰ্থ প’ৰ্টেল",
    lpScheme1Desc: "ব্যৱসায়িক ঋণৰ বাবে ভাৰত চৰকাৰৰ অফিচিয়েল প’ৰ্টেল",
    lpScheme2Name: "উদ্যম নিবন্ধন",
    lpScheme2Desc: "MSME নিবন্ধনৰ অফিচিয়েল প’ৰ্টেল",
    lpScheme3Name: "ষ্টাৰ্টআপ ইণ্ডিয়া",
    lpScheme3Desc: "ষ্টাৰ্টআপৰ বাবে চৰকাৰী সহায়",
    lpDisclaimer: "এইবোৰ চৰকাৰী ৱেবছাইট। আমি ফলাফলৰ নিশ্চয়তা নিদিওঁ।",
    lpContinueEquity: "ইক্যুইটিৰ সৈতে আগবাঢ়ক →",
  },
  mr: {
    back: "← परत",
    screen: "पद",
    of: "चे",
    landingTitle: "आम्ही तुमच्या व्यवसायाला वाढवू शकतो",
    landingSub:
      "Quiver लहान व्यवसायांसह भागीदारी करते: निधी, मार्गदर्शन आणि आवश्यक साधने।",
    landingCTA: "पुढे जा →",
    landingFunding: "निधी",
    landingFundingSub: "स्केल करण्यासाठी योग्य वेळी पैसे",
    landingMentorship: "मार्गदर्शन",
    landingMentorshipSub: "योग्य निर्णय घेण्यासाठी मेंटरशिप",
    landingTools: "शिक्षा आणि साधने",
    landingToolsSub: "शिका आणि तुमचा व्यवसाय चालणे सुधारा",
    s1Title: "आज तुमचा व्यवसाय",
    s1Sub: "तुमच्या व्यवसायाबद्दल सांगा आणि आम्ही तुम्हाला वाढीचा मार्ग दाखवू।",
    s1Sales: "मासिक विक्रय (₹)",
    s1Margin: "नफा मार्जिन (%)",
    s1MarginHint: "उदाहरणार्थ, 20 म्हणजे विक्रयातून तुमचा 20% नफा",
    s1Investment: "व्यवसाय वाढवण्यासाठी भांडवल (₹)",
    s1Profit: "मासिक नफा",
    s1Insight: (m, inv) => `या गतीने, ₹${inv} मिळवायला ${m} महिने लागतील।`,
    s2Insight: (m, inv) => `या गतीने, ₹${inv} मिळवायला ${m} महिने लागतील।`,
    s1CTA: "माझा व्यवसाय वाढवा →",
    s2Title: (inv) => `तुम्हाला ₹${inv} विस्तारासाठी आवश्यक`,
    s2Sub: "दोन मार्ग. एक प्रत्येक महिने खर्च करतो. दुसरा तुमच्यासोबत वाढतो.",
    s2Income: (i) => `तुमचा सद्य नफा: ₹${i}/महिना`,
    s2Loan: "बँक कर्ज",
    s2LoanSub: "प्रत्येक महिने निश्चित EMI",
    s2LoanDesc:
      "व्यवसाय चांगला असो किंवा वाईट — एकच निश्चित रक्कम द्यावी लागते।",
    s2Partner: "भागीदारी",
    s2PartnerBadge: "सुचवलेले",
    s2PartnerSub:
      "कोई EMI नहीं. तुमचा साथी फक्त तेव्हाच कमावतो जेव्हा तुम्ही कमावता.",
    s2PartnerDesc: "भांडवल + मेंटरशिप + बाजार संपर्क — सब एक ठिकाणी।",
    s2SeeEMI: "EMI तपशील पहा →",
    s2Continue: "भागीदारी समजून घ्या →",
    s2Change: "बदला",
    s2TblCapital: "विस्तारासाठी भांडवल",
    s2TblCollateral: "कर्जाचे समर्थन",
    s2TblFixedEmi: "प्रत्येक महिने निश्चित EMI",
    s2TblMentorship: "मेंटरशिप / मार्गदर्शन",
    s2TblEducationTools: "शिक्षा आणि साधने",
    s2TblMarketLinkage: "बाजार संपर्क / नेटवर्क",
    sEMITitle: "कर्ज मधील",
    sEMISub: "परतफेड योजना शोधा",
    sEMIDuration: "परतफेड मुदत",
    sEMIRateLabel: "व्याज दर",
    sEMIYrs: "वर्ष",
    sEMILoan: "कर्जाची रक्कम",
    sEMIRate: "व्याज दर",
    sEMIMonthly: "मासिक EMI",
    sEMIInterest: "एकूण व्याज",
    sEMITotal: "एकूण भरावयाचे",
    sEMIAfter: "हातात रोकड",
    sEMIPartner: "भागीदारी पहा →",
    sEMIContinue: "कर्जासह पुढे जा",
    s3Title: "इक्विटी कसे कार्य करते",
    s3HeroSub: "मीनाच्या संघर्षातून वाढीचा प्रवास अनुसरण करा",
    s3Tag1: "व्यवसाय",
    s3Title1: "मीनाचे शिलाई युनिट",
    s3MonthlyIncome: "मासिक उत्पन्न",
    s3FundingNeeded: "आवश्यक निधी",
    s3Tag2: "समस्या",
    s3Title2: "कर्ज सोपे नाही",
    s3Prob1: "बँक समर्थन मागते",
    s3Prob2: "प्रत्येक महिने EMI दबाव",
    s3Prob3: "व्याज नफा कमी करतो",
    s3Tag3: "समाधान",
    s3Title3: "इक्विटी भागीदार येतो",
    s3Investment: "गुंतवणूक",
    s3ExitAfter: "बाहेर पडा",
    s3ExitVal: "5 वर्ष",
    s3Tag4: "इक्विटी विभाजन",
    s3Title4: "तिनी नियंत्रण ठेवते",
    s3MeenaControl: "मीना — पूर्ण नियंत्रण",
    s3InvestorPartner: "गुंतवणूकदार भागीदार",
    s3TagRisk: "सामायिक धोका",
    s3TitleRisk: "जर व्यवसाय मंदावला तर...",
    s3Risk1: "मीना नुकसानीत एकटी नाही",
    s3Risk2: "तिचा भागीदारही तोटा शेअर करतो",
    s3Risk3: "दोघे मिळून सुधारणा करतात आणि पुन्हा उभे राहतात",
    s3Tag5: "परिणाम",
    s3Title5: "मीनाचा व्यवसाय वाढतो",
    s3Out1: "नई मशीने खरीदी",
    s3Out2: "मोठे क्लायंट आणि अधिक ऑर्डर",
    s3Out3: "गुंतवणूकदार नेटवर्क आणि मार्गदर्शन आणते",
    s3CTA: "पुढे जा →",
    s5JourneyTitle: "तुमचा प्रवास सुरू करा",
    s5JourneyHighlight: "आज",
    s5JourneySub:
      "तुम्ही पाहिले की इक्विटी तुमचा व्यवसाय कसे वाढवू शकते. Quiver सोबत पुढील पायरी घ्या.",
    s5GetStarted: "सुरू करा",
    s5ApplyTitle: "Quiver वर अर्ज करा",
    s5ApplySub: "तुमचे ऑनबोर्डिंग सुरू करा",
    s5LearnTitle: "अधिक जानें",
    s5LearnSub: "तुमचा व्यवसाय कसे काम करते हे जानने के लिए quiver.in पर जाएं",
    s5Or: "किंवा",
    s5Restart: "← भिन्न संख्यांसह पुन्हा सुरू करा",
    lpExploreTitle: "सरकारी योजना शोधा",
    lpExploreSub:
      "पात्रता तपासण्यासाठी आणि थेट अर्ज करण्यासाठी हे अधिकृत सरकारी पोर्टल पहा।",
    lpScheme1Name: "जनसमर्थ पोर्टल",
    lpScheme1Desc: "व्यवसाय कर्ज योजनांसाठी भारत सरकारचे अधिकृत पोर्टल",
    lpScheme2Name: "उद्यम नोंदणी",
    lpScheme2Desc: "MSME मंत्रालयाचे अधिकृत MSME नोंदणी पोर्टल",
    lpScheme3Name: "स्टार्टअप इंडिया",
    lpScheme3Desc: "स्टार्टअप निधी आणि समर्थनासाठी सरकारी उपक्रम",
    lpDisclaimer:
      "हे अधिकृत सरकारी वेबसाइट आहेत. आम्ही पात्रता किंवा परिणामांची हमी देत नाही.",
    lpContinueEquity: "त्याऐवजी इक्विटीसह जारी ठेवा →",
  },
};

export { T, fmt };
