const fmt = (n) => Number(n).toLocaleString("en-IN");
// ─── TRANSLATIONS ────────────────────────────────────────────────────────────
const T = {
  en: {
    // Common
    back: "← Back",
    screen: "Step",
    of: "of",
    // Landing
    landingTitle: "We help your business grow",
    landingSub: "Quiver partners with small businesses with funding, guidance, and tools you actually need.",
    landingCTA: "Continue →",
    landingFunding: "Funding",
    landingFundingSub: "Money when you need to scale",
    landingMentorship: "Guidance",
    landingMentorshipSub: "Mentorship to make the right decisions",
    landingTools: "Education & Tools",
    landingToolsSub: "Learn and improve how you run the business",
    // Screen 1
    s1Title: "Your Business Today",
    s1Sub: "Tell us about your business and we'll show you exactly how to grow it.",
    s1Sales: "Monthly Sales (₹)",
    s1Margin: "Profit Margin (%)",
    s1MarginHint: "e.g. 20 means you keep 20% of sales as profit",
    s1Investment: "Capital Needed to Grow (₹)",
    s1Profit: "Your Monthly Profit",
    s1Insight: (m, inv) => `At this pace, even reinvesting your entire profit will take ${m} months to save ₹${inv}.`,
    s2Insight: (m, inv) => `Reinvesting your entire profit will take ${m} months to save ₹${inv}.`,
    s1CTA: "Grow My Business →",
    // Screen 2
    s2Title: (inv) => `You need ₹${inv} to expand`,
    s2Sub: "Two paths. One costs you monthly. One grows with you.",
    s2Income: (i) => `Your current profit: ₹${i}/month`,
    s2Loan: "Bank Loan",
    s2LoanSub: "Fixed EMI every month",
    s2LoanDesc: "Whether business is good or bad — you pay the same fixed amount.",
    s2Partner: "Quiver Partnership",
    s2PartnerBadge: "Recommended",
    s2PartnerSub: "No fixed EMI. Your partner earns when you earn.",
    s2PartnerDesc: "Capital + Mentorship + Market Linkage — all in one.",
    s2SeeEMI: "See EMI Details →",
    s2Continue: "Explore Partnership →",
    s2Change: "Change",
    // Step 2 - table comparison
    s2TblCapital: "Capital to expand",
    s2TblCollateral: "Collateral required",
    s2TblFixedEmi: "Fixed EMI every month",
    s2TblMentorship: "Mentorship / guidance",
    s2TblEducationTools: "Education & Tools",
    s2TblMarketLinkage: "Market linkage / network",
    // Screen EMI
    sEMITitle: "Loan Calculator",
    sEMISub: "Explore repayment plans",
    sEMIDuration: "Repayment Duration",
    sEMIYrs: "yrs",
    sEMILoan: "Loan Amount",
    sEMIRate: "Interest Rate",
    sEMIMonthly: "Monthly EMI",
    sEMIInterest: "Total Interest",
    sEMITotal: "Total Payable",
    sEMIAfter: "Cash in hand",
    sEMIPartner: "Explore Partnership →",
    sEMIContinue: "Proceed with Loan",
    // Screen 3
    s3Title: "How Equity Works",
    s3HeroSub: "Follow Meena's journey from struggle to growth",
    s3Tag1: "The Business", s3Title1: "Meena's Tailoring Unit",
    s3MonthlyIncome: "Monthly Income", s3FundingNeeded: "Funding Needed",
    s3Tag2: "The Problem", s3Title2: "Loans Aren't Easy",
    s3Prob1: "Banks ask for collateral", s3Prob2: "EMI pressure every month", s3Prob3: "High interest cuts profits",
    s3Tag3: "The Solution", s3Title3: "An Equity Partner Steps In",
    s3Investment: "Investment", s3ExitAfter: "Exit After", s3ExitVal: "5 Years",
    s3Tag4: "Equity Split", s3Title4: "She Keeps Control",
    s3MeenaControl: "Meena — Full control", s3InvestorPartner: "Investor partner",
    s3Tag5: "The Outcome", s3Title5: "Meena's Business Grows",
    s3Out1: "New machines purchased", s3Out2: "Bigger clients & more orders", s3Out3: "Investor brings network & guidance",
    s3CTA: "Continue →",
    // Screen 4
    s5JourneyTitle: "Start Your Journey",
    s5JourneyHighlight: "Today",
    s5JourneySub: "You've seen how equity can grow your business. Take the next step with Quiver.",
    s5GetStarted: "Get started",
    s5ApplyTitle: "Apply on Quiver",
    s5ApplySub: "Start your onboarding",
    s5LearnTitle: "Learn More",
    s5LearnSub: "Visit quiver.in to explore how it works",
    s5Or: "or",
    s5Restart: "← Start over with different numbers",
    // Loan Prep
    lpExploreTitle: "Explore Official Schemes",
    lpExploreSub: "Visit these official government portals to check eligibility and apply directly.",
    lpScheme1Name: "Jansamarth Portal",
    lpScheme1Desc: "Official Government of India portal for business loan schemes",
    lpScheme2Name: "Udyam Registration",
    lpScheme2Desc: "Official MSME registration portal by Ministry of MSME",
    lpScheme3Name: "Startup India",
    lpScheme3Desc: "Government initiative for startup funding & support",
    lpDisclaimer: "These are official government websites. We do not guarantee eligibility or outcomes.",
    lpContinueEquity: "Continue with Equity Instead →",
  },
  hi: {
    back: "← वापस",
    screen: "चरण",
    of: "का",
    // Landing
    landingTitle: "हम आपका बिज़नेस बढ़ाते हैं",
    landingSub: "Quiver छोटे व्यवसायों के साथ साझेदारी करता है: पैसा, मार्गदर्शन और ज़रूरी टूल्स।",
    landingCTA: "जारी रखें →",
    landingFunding: "फंडिंग",
    landingFundingSub: "स्केल करने के लिए सही समय पर पैसा",
    landingMentorship: "मार्गदर्शन",
    landingMentorshipSub: "सही फैसले के लिए मेंटरशिप",
    landingTools: "शिक्षा और टूल्स",
    landingToolsSub: "सीखें और अपने बिज़नेस को बेहतर चलाएं",
    s1Title: "आपका व्यवसाय आज",
    s1Sub: "अपने व्यवसाय के बारे में बताएं और हम आपको बढ़ने का तरीका दिखाएंगे।",
    s1Sales: "मासिक बिक्री (₹)",
    s1Margin: "लाभ मार्जिन (%)",
    s1MarginHint: "जैसे 20 का मतलब है बिक्री का 20% आपका लाभ",
    s1Investment: "व्यवसाय बढ़ाने के लिए पूंजी (₹)",
    s1Profit: "मासिक लाभ",
    s1Challenges: "आपकी चुनौतियाँ",
    s1Insight: (m, inv) => `इस गति से, ₹${inv} बचाने में ${m} महीने लगेंगे।`,
    s2Insight: (m, inv) => `इस गति से, ₹${inv} बचाने में ${m} महीने लगेंगे।`,
    s1InsightSub: (y) => `${y} साल का इंतजार — एक बेहतर रास्ता है।`,
    s1CTA: "मेरा व्यवसाय बढ़ाएं →",
    s2Title: (inv) => `आपको ₹${inv} की जरूरत है`,
    s2Sub: "दो रास्ते। एक हर महीने खर्च करता है। एक आपके साथ बढ़ता है।",
    s2Income: (i) => `आपका मौजूदा लाभ: ₹${i}/महीना`,
    s2Loan: "बैंक ऋण",
    s2LoanSub: "हर महीने तय EMI",
    s2LoanDesc: "चाहे व्यवसाय अच्छा हो या बुरा — एक ही तय राशि देनी होगी।",
    s2Partner: "Quiver साझेदारी",
    s2PartnerBadge: "अनुशंसित",
    s2PartnerSub: "कोई EMI नहीं। आपका साथी तभी कमाता है जब आप कमाते हैं।",
    s2PartnerDesc: "पूंजी + मेंटरशिप + बाजार संपर्क — सब एक जगह।",
    s2SeeEMI: "EMI विवरण देखें →",
    s2Continue: "साझेदारी समझें →",
    s2Change: "बदलें",
    // Step 2 - table comparison
    s2TblCapital: "स्केल करने के लिए पूंजी",
    s2TblCollateral: "लोन के लिए कोलैटरल",
    s2TblFixedEmi: "हर महीने फिक्स्ड EMI",
    s2TblMentorship: "मेंटरशिप / मार्गदर्शन",
    s2TblEducationTools: "शिक्षा और टूल्स",
    s2TblMarketLinkage: "बाजार संपर्क / नेटवर्क",
    sEMITitle: "ऋण कैलकुलेटर",
    sEMISub: "पुनर्भुगतान योजना चुनें",
    sEMIDuration: "पुनर्भुगतान अवधि",
    sEMIYrs: "वर्ष",
    sEMILoan: "ऋण राशि",
    sEMIRate: "ब्याज दर",
    sEMIMonthly: "मासिक EMI",
    sEMIInterest: "कुल ब्याज",
    sEMITotal: "कुल भुगतान",
    sEMIAfter: "EMI के बाद शेष",
    sEMIPartner: "साझेदारी देखें →",
    sEMIContinue: "ऋण के साथ आगे बढ़ें",

    s3Title: "इक्विटी कैसे काम करती है",
    s3HeroSub: "मीना की संघर्ष से विकास तक की यात्रा",
    s3Tag1: "व्यवसाय", s3Title1: "मीना की टेलरिंग यूनिट",
    s3MonthlyIncome: "मासिक आय", s3FundingNeeded: "जरूरी पूंजी",
    s3Tag2: "समस्या", s3Title2: "लोन आसान नहीं है",
    s3Prob1: "बैंक गारंटी मांगता है", s3Prob2: "हर महीने EMI का बोझ", s3Prob3: "ब्याज से मुनाफा कम होता है",
    s3Tag3: "समाधान", s3Title3: "एक इक्विटी पार्टनर आता है",
    s3Investment: "निवेश", s3ExitAfter: "बाहर निकलने का समय", s3ExitVal: "5 साल",
    s3Tag4: "इक्विटी बंटवारा", s3Title4: "वह नियंत्रण रखती है",
    s3MeenaControl: "मीना — पूरा नियंत्रण", s3InvestorPartner: "निवेशक साथी",
    s3Tag5: "परिणाम", s3Title5: "मीना का व्यवसाय बढ़ता है",
    s3Out1: "नई मशीनें खरीदी गईं", s3Out2: "बड़े ग्राहक और ज्यादा ऑर्डर", s3Out3: "निवेशक नेटवर्क और मार्गदर्शन लाता है",
    s3CTA: "आगे बढ़ें →",

    s5JourneyTitle: "अपनी यात्रा शुरू करें",
    s5JourneyHighlight: "आज",
    s5JourneySub: "आपने देखा कि इक्विटी आपका व्यवसाय कैसे बढ़ा सकती है। Quiver के साथ अगला कदम उठाएं।",
    s5GetStarted: "शुरू करें",
    s5ApplyTitle: "Quiver पर आवेदन करें",
    s5ApplySub: "अपना ऑनबोर्डिंग शुरू करें",
    s5LearnTitle: "और जानें",
    s5LearnSub: "यह कैसे काम करता है जानने के लिए quiver.in पर जाएं",
    s5Or: "या",
    s5Restart: "← अलग नंबरों के साथ दोबारा शुरू करें",

    lpExploreTitle: "सरकारी योजनाएं देखें",
    lpExploreSub: "पात्रता जांचने और सीधे आवेदन करने के लिए इन आधिकारिक सरकारी पोर्टल पर जाएं।",
    lpScheme1Name: "जनसमर्थ पोर्टल",
    lpScheme1Desc: "व्यवसाय ऋण योजनाओं के लिए भारत सरकार का आधिकारिक पोर्टल",
    lpScheme2Name: "उद्यम पंजीकरण",
    lpScheme2Desc: "MSME मंत्रालय का आधिकारिक MSME पंजीकरण पोर्टल",
    lpScheme3Name: "स्टार्टअप इंडिया",
    lpScheme3Desc: "स्टार्टअप फंडिंग और सहायता के लिए सरकारी पहल",
    lpDisclaimer: "ये आधिकारिक सरकारी वेबसाइटें हैं। हम पात्रता या परिणामों की गारंटी नहीं देते।",
    lpContinueEquity: "इसके बजाय इक्विटी के साथ आगे बढ़ें →",
  }
};

export { T, fmt };